local pokemontype = {}

pokemontype.Normal = {}
pokemontype.Fire = {}
pokemontype.Water = {}
pokemontype.Electric = {}
pokemontype.Grass = {}
pokemontype.Ice = {}
pokemontype.Fighting = {}
pokemontype.Poison = {}
pokemontype.Ground = {}
pokemontype.Flying = {}
pokemontype.Psychic = {}
pokemontype.Bug = {}
pokemontype.Rock = {}
pokemontype.Ghost = {}
pokemontype.Dragon = {}
pokemontype.Dark = {}
pokemontype.Steel = {}
pokemontype.Fairy = {}
pokemontype.Normal[pokemontype.Normal] = 1
pokemontype.Normal[pokemontype.Fire] = 1
pokemontype.Normal[pokemontype.Water] = 1
pokemontype.Normal[pokemontype.Electric] = 1
pokemontype.Normal[pokemontype.Grass] = 1
pokemontype.Normal[pokemontype.Ice] = 1
pokemontype.Normal[pokemontype.Fighting] = 1
pokemontype.Normal[pokemontype.Poison] = 1
pokemontype.Normal[pokemontype.Ground] = 1
pokemontype.Normal[pokemontype.Flying] = 1
pokemontype.Normal[pokemontype.Psychic] = 1
pokemontype.Normal[pokemontype.Bug] = 1
pokemontype.Normal[pokemontype.Rock] = 0.5
pokemontype.Normal[pokemontype.Ghost] = 0
pokemontype.Normal[pokemontype.Dragon] = 1
pokemontype.Normal[pokemontype.Dark] = 1
pokemontype.Normal[pokemontype.Steel] = 0.5
pokemontype.Normal[pokemontype.Fairy] = 1
pokemontype.Fire[pokemontype.Normal] = 1
pokemontype.Fire[pokemontype.Fire] = 0.5
pokemontype.Fire[pokemontype.Water] = 0.5
pokemontype.Fire[pokemontype.Electric] = 1
pokemontype.Fire[pokemontype.Grass] = 2
pokemontype.Fire[pokemontype.Ice] = 2
pokemontype.Fire[pokemontype.Fighting] = 1
pokemontype.Fire[pokemontype.Poison] = 1
pokemontype.Fire[pokemontype.Ground] = 1
pokemontype.Fire[pokemontype.Flying] = 1
pokemontype.Fire[pokemontype.Psychic] = 1
pokemontype.Fire[pokemontype.Bug] = 2
pokemontype.Fire[pokemontype.Rock] = 0.5
pokemontype.Fire[pokemontype.Ghost] = 1
pokemontype.Fire[pokemontype.Dragon] = 0.5
pokemontype.Fire[pokemontype.Dark] = 1
pokemontype.Fire[pokemontype.Steel] = 2
pokemontype.Fire[pokemontype.Fairy] = 1
pokemontype.Water[pokemontype.Normal] = 1
pokemontype.Water[pokemontype.Fire] = 2
pokemontype.Water[pokemontype.Water] = 0.5
pokemontype.Water[pokemontype.Electric] = 1
pokemontype.Water[pokemontype.Grass] = 0.5
pokemontype.Water[pokemontype.Ice] = 1
pokemontype.Water[pokemontype.Fighting] = 1
pokemontype.Water[pokemontype.Poison] = 1
pokemontype.Water[pokemontype.Ground] = 2
pokemontype.Water[pokemontype.Flying] = 1
pokemontype.Water[pokemontype.Psychic] = 1
pokemontype.Water[pokemontype.Bug] = 1
pokemontype.Water[pokemontype.Rock] = 2
pokemontype.Water[pokemontype.Ghost] = 1
pokemontype.Water[pokemontype.Dragon] = 0.5
pokemontype.Water[pokemontype.Dark] = 1
pokemontype.Water[pokemontype.Steel] = 1
pokemontype.Water[pokemontype.Fairy] = 1
pokemontype.Electric[pokemontype.Normal] = 1
pokemontype.Electric[pokemontype.Fire] = 1
pokemontype.Electric[pokemontype.Water] = 2
pokemontype.Electric[pokemontype.Electric] = 0.5
pokemontype.Electric[pokemontype.Grass] = 0.5
pokemontype.Electric[pokemontype.Ice] = 1
pokemontype.Electric[pokemontype.Fighting] = 1
pokemontype.Electric[pokemontype.Poison] = 1
pokemontype.Electric[pokemontype.Ground] = 0
pokemontype.Electric[pokemontype.Flying] = 2
pokemontype.Electric[pokemontype.Psychic] = 1
pokemontype.Electric[pokemontype.Bug] = 1
pokemontype.Electric[pokemontype.Rock] = 1
pokemontype.Electric[pokemontype.Ghost] = 1
pokemontype.Electric[pokemontype.Dragon] = 0.5
pokemontype.Electric[pokemontype.Dark] = 1
pokemontype.Electric[pokemontype.Steel] = 1
pokemontype.Electric[pokemontype.Fairy] = 1
pokemontype.Grass[pokemontype.Normal] = 1
pokemontype.Grass[pokemontype.Fire] = 0.5
pokemontype.Grass[pokemontype.Water] = 2
pokemontype.Grass[pokemontype.Electric] = 1
pokemontype.Grass[pokemontype.Grass] = 0.5
pokemontype.Grass[pokemontype.Ice] = 1
pokemontype.Grass[pokemontype.Fighting] = 1
pokemontype.Grass[pokemontype.Poison] = 0.5
pokemontype.Grass[pokemontype.Ground] = 2
pokemontype.Grass[pokemontype.Flying] = 0.5
pokemontype.Grass[pokemontype.Psychic] = 1
pokemontype.Grass[pokemontype.Bug] = 0.5
pokemontype.Grass[pokemontype.Rock] = 2
pokemontype.Grass[pokemontype.Ghost] = 1
pokemontype.Grass[pokemontype.Dragon] = 0.5
pokemontype.Grass[pokemontype.Dark] = 1
pokemontype.Grass[pokemontype.Steel] = 0.5
pokemontype.Grass[pokemontype.Fairy] = 1
pokemontype.Ice[pokemontype.Normal] = 1
pokemontype.Ice[pokemontype.Fire] = 0.5
pokemontype.Ice[pokemontype.Water] = 0.5
pokemontype.Ice[pokemontype.Electric] = 1
pokemontype.Ice[pokemontype.Grass] = 2
pokemontype.Ice[pokemontype.Ice] = 0.5
pokemontype.Ice[pokemontype.Fighting] = 1
pokemontype.Ice[pokemontype.Poison] = 1
pokemontype.Ice[pokemontype.Ground] = 2
pokemontype.Ice[pokemontype.Flying] = 2
pokemontype.Ice[pokemontype.Psychic] = 1
pokemontype.Ice[pokemontype.Bug] = 1
pokemontype.Ice[pokemontype.Rock] = 1
pokemontype.Ice[pokemontype.Ghost] = 1
pokemontype.Ice[pokemontype.Dragon] = 2
pokemontype.Ice[pokemontype.Dark] = 1
pokemontype.Ice[pokemontype.Steel] = 0.5
pokemontype.Ice[pokemontype.Fairy] = 1
pokemontype.Fighting[pokemontype.Normal] = 2
pokemontype.Fighting[pokemontype.Fire] = 1
pokemontype.Fighting[pokemontype.Water] = 1
pokemontype.Fighting[pokemontype.Electric] = 1
pokemontype.Fighting[pokemontype.Grass] = 1
pokemontype.Fighting[pokemontype.Ice] = 2
pokemontype.Fighting[pokemontype.Fighting] = 1
pokemontype.Fighting[pokemontype.Poison] = 0.5
pokemontype.Fighting[pokemontype.Ground] = 1
pokemontype.Fighting[pokemontype.Flying] = 0.5
pokemontype.Fighting[pokemontype.Psychic] = 0.5
pokemontype.Fighting[pokemontype.Bug] = 0.5
pokemontype.Fighting[pokemontype.Rock] = 2
pokemontype.Fighting[pokemontype.Ghost] = 0
pokemontype.Fighting[pokemontype.Dragon] = 1
pokemontype.Fighting[pokemontype.Dark] = 2
pokemontype.Fighting[pokemontype.Steel] = 2
pokemontype.Fighting[pokemontype.Fairy] = 0.5
pokemontype.Poison[pokemontype.Normal] = 1
pokemontype.Poison[pokemontype.Fire] = 1
pokemontype.Poison[pokemontype.Water] = 1
pokemontype.Poison[pokemontype.Electric] = 1
pokemontype.Poison[pokemontype.Grass] = 1
pokemontype.Poison[pokemontype.Ice] = 1
pokemontype.Poison[pokemontype.Fighting] = 1
pokemontype.Poison[pokemontype.Poison] = 1
pokemontype.Poison[pokemontype.Ground] = 1
pokemontype.Poison[pokemontype.Flying] = 1
pokemontype.Poison[pokemontype.Psychic] = 1
pokemontype.Poison[pokemontype.Bug] = 1
pokemontype.Poison[pokemontype.Rock] = 1
pokemontype.Poison[pokemontype.Ghost] = 1
pokemontype.Poison[pokemontype.Dragon] = 1
pokemontype.Poison[pokemontype.Dark] = 1
pokemontype.Poison[pokemontype.Steel] = 1
pokemontype.Poison[pokemontype.Fairy] = 1
-- pokemontype.Ground = 9
-- pokemontype.Flying = 10
-- pokemontype.Psychic = 11
-- pokemontype.Bug = 12
-- pokemontype.Rock = 13
-- pokemontype.Ghost = 14
-- pokemontype.Dragon = 15
-- pokemontype.Dark = 16
-- pokemontype.Steel = 17
-- pokemontype.Fairy = 18

-- local base = {
--     [pokemontype.Normal] = 1
--     [pokemontype.Fire] = 1
--     [pokemontype.Water] = 1
--     [pokemontype.Electric] = 1
--     [pokemontype.Grass] = 1
--     [pokemontype.Ice] = 1
--     [pokemontype.Fighting] = 1
--     [pokemontype.Poison] = 1
--     [pokemontype.Ground] = 1
--     [pokemontype.Flying] = 1
--     [pokemontype.Psychic] = 1
--     [pokemontype.Bug] = 1
--     [pokemontype.Rock] = 1
--     [pokemontype.Ghost] = 1
--     [pokemontype.Dragon] = 1
--     [pokemontype.Dark] = 1
--     [pokemontype.Steel] = 1
--     [pokemontype.Fairy] = 1
-- }
print(pokemontype.Normal[pokemontype.Fire])
return pokemontype